kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: accounts-db
  labels:
    {{- include "bank-of-anthos.labels" . | nindent 4 }}
    app: accounts-db
    tier: db
spec:
  serviceName: "accounts-db"
  replicas: 1
  selector:
    matchLabels:
      {{- include "bank-of-anthos.selectorLabels" . | nindent 6 }}
      app: accounts-db
      tier: db
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
      labels:
        {{- include "bank-of-anthos.selectorLabels" . | nindent 8 }}
        app: accounts-db
        tier: db
    spec:
      serviceAccountName: default
      containers:
      - name: accounts-db
        image: {{.Values.accountsdb.image}}
        envFrom:
          {{- tpl .Values.accountsdb.envFrom . | nindent 12 }}
        ports:
          - containerPort: {{ .Values.accountsdb.port }}
            name: postgredb
        {{- if .Values.accountsdb.resources }}
        resources:
          {{- toYaml .Values.accountsdb.resources | nindent 12 }}
        {{- end }}
        volumeMounts:
        - name: postgresdb
          mountPath: /var/lib/postgresql/data
          subPath: postgres
      volumes:
      - name: postgresdb
        emptyDir: {}