{{- range $config := .Values.configMaps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $config.name}}
  {{- if $config.label }}
  labels:
    {{- toYaml $config.label | nindent 4 }}
  {{- end }}
data:
  {{- toYaml $config.data | nindent 2 }}
---
{{- end }}
