# This directory contains a pre-built [Secret](https://kubernetes.io/docs/concepts/configuration/secret/) 
# containing an RSA key pair to make deployment easier.

{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: jwt-key
type: Opaque
data:
  jwtRS256.key: {{ required ".Values.secret.jwtRS256Key is required" .Values.secret.jwtRS256Key }}
  jwtRS256.key.pub: {{ required ".Values.secret.jwtRS256KeyPub is required" .Values.secret.jwtRS256KeyPub }} 
{{- end }}