{{- range $statefulset := .Values.statefulset }}
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: {{ $statefulset.name }}
  labels:
    {{- include "bank-of-anthos.labels" $ | nindent 4 }}
    app: {{ $statefulset.app }}
    tier: db
spec:
  {{- if $statefulset.serviceName }}
  serviceName: {{ $statefulset.serviceName }}
  {{- end }}
  replicas: {{ $statefulset.replicas }}
  selector:
    matchLabels:
      {{- include "bank-of-anthos.selectorLabels" $ | nindent 6 }}
      app: {{ $statefulset.app }}
      tier: db
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmaps.yaml") $ | sha256sum }}
        {{- if $statefulset.podAnnotations }}
        {{- toYaml $statefulset.podAnnotations | nindent 8 }}
        {{- end }}
      labels:
        {{- include "bank-of-anthos.selectorLabels" $ | nindent 8 }}
        app: {{ $statefulset.app }}
        tier: db
    spec:
      serviceAccountName: {{ $statefulset.serviceAccountName }}
      containers:
      - name: {{ $statefulset.container.name }}
        image: {{$statefulset.container.image}}:{{ $.Values.appVersion }}
        envFrom:
          {{- tpl $statefulset.container.envFrom $ | nindent 12 }}
        {{- if $statefulset.port }}
        ports:
          {{ toYaml $statefulset.port | nindent 12 }}
        {{- end }}
        {{- if $statefulset.resources }}
        resources:
          {{- toYaml $statefulset.resources | nindent 12 }}
        {{- end }}
        {{- if $statefulset.container.volumeMounts }}
        volumeMounts:
        {{ toYaml $statefulset.container.volumeMounts | nindent 12}}
        {{- end }}
      {{- if $statefulset.volumes }}
      volumes:
      {{ toYaml $statefulset.volumes | nindent 10}}
      {{- end }}
{{- end }}